ruta_csv_inicial = '../Data/df_util_sin_bebidas.csv'
ruta_csv_cesta ='../Data/resultados_api.csv'


productos = [
    "arroz redondo",
    "pan integral",
    "panecillo integral",
    "spaghetti",
    "carpaccio",
    "filete de lomo de cerdo",
    "costillas de cordero",
    "filete de pechuga de pavo",
    "jamon serrano",
    "callos de ternera",
    "hamburguesa de vacuno",
    "patas de pollo",
    "filetes de lubina",
    "varitas de merluza empanadas",
    "mejillones al natural",
    "salmon ahumado",
    "mejillones en escabeche",
    "leche entera asturiana",
    "leche desnatada",
    "yogur natural",
    "garcia vaquero",
    "queso fresco 0%",
    "huevos frescos",
    "mantequilla tradicional",
    "aceite de girasol",
    "aceite de oliva virgen extra",
    "aceite de coco virgen",
    "manteca de cerdo",
    "peras",
    "datiles",
    "aceitunas rellenas de anchoa",
    "bayas de goji",
    "arandanos deshidratados",
    "cacahuetes tostados salados",
    "smoothie fresa",
    "cebolleta roja",
    "coliflor",
    "calabacines union",
    "palitos de zanahoria",
    "lentejas",
    "coliflor brocoli y zanahoria",
    "garbanzos cocidos",
    "patatas udapa",
    "patatas para tortilla",
    "azucar blanco",
    "snickers",
    "toblerone",
    "helado de pistacho",
    "gominolas",
    "gran aroma natural",
    "te jengibre limon",
    "colacao",
    "agua mineral",
    "coca cola",
    "zumo de manzana",
    "zumo de tomate"
]

lista_columnas = ['product_name_es',
 'quantity',
 'serving_size',
 'brands',
 'categories',
 'stores',
 'nutrition_data_per',
 'nutrition_data_prepared_per',
 'energy-kcal_value',
 'energy-kcal_unit',
 'energy-kcal_prepared_value',
 'energy-kcal_prepared_unit',
 'fat_value',
 'fat_unit',
 'saturated-fat_value',
 'saturated-fat_unit',
 'carbohydrates_value',
 'carbohydrates_unit',
 'sugars_value',
 'sugars_unit',
 'fiber_value',
 'fiber_unit',
 'proteins_value',
 'proteins_unit',
 'salt_value',
 'salt_unit',
 'sodium_value',
 'sodium_unit',
 'energy_value',
 'energy_unit',
 'off:food_groups',
 'off:food_groups_tags',
 'off:nova_groups',
 'off:nova_groups_tags',
 'off:nutriscore_grade']

# Este diccionario mapea una palabra clave (en minúsculas) encontrada en la cadena de categorías
# a una categoría principal de Nivel 1.

category_mapping = {
    # 🥛 LÁCTEOS Y HUEVOS
    "lácteos": "Lácteos y Derivados", "queso": "Lácteos y Derivados", "yogur": "Lácteos y Derivados",
    "leche": "Lácteos y Derivados", "mantequilla": "Lácteos y Derivados", "huevos": "Lácteos y Derivados",
    "nata": "Lácteos y Derivados", "kéfir": "Lácteos y Derivados", "petit": "Lácteos y Derivados",
    "mozzarella": "Lácteos y Derivados", "kefir traditional": "Lácteos y Derivados", "quescrem": "Lácteos y Derivados",

    # 🍖 CARNE, AVES Y PRODUCTOS CÁRNICOS
    "carne": "Carne, Aves y Productos Cárnicos", "carnes frías": "Carne, Aves y Productos Cárnicos",
    "pollo": "Carne, Aves y Productos Cárnicos", "ternera": "Carne, Aves y Productos Cárnicos",
    "cerdo": "Carne, Aves y Productos Cárnicos", "jamón": "Carne, Aves y Productos Cárnicos",
    "bacon": "Carne, Aves y Productos Cárnicos", "hamburguesas": "Carne, Aves y Productos Cárnicos",
    "salchichas": "Carne, Aves y Productos Cárnicos", "butifarra": "Carne, Aves y Productos Cárnicos",
    "pechuga de pavo": "Carne, Aves y Productos Cárnicos", "burger": "Carne, Aves y Productos Cárnicos",
    "secreto": "Carne, Aves y Productos Cárnicos", "torreznos": "Carne, Aves y Productos Cárnicos",
    "alitas": "Carne, Aves y Productos Cárnicos", "lomo embuchado": "Carne, Aves y Productos Cárnicos",
    "chorizo": "Carne, Aves y Productos Cárnicos", "salchichón": "Carne, Aves y Productos Cárnicos",
    "fiambre": "Carne, Aves y Productos Cárnicos", "espetec": "Carne, Aves y Productos Cárnicos",
    "pavo marinado": "Carne, Aves y Productos Cárnicos", "carnitas de cerdo": "Carne, Aves y Productos Cárnicos",
    "fuet": "Carne, Aves y Productos Cárnicos", "lomo curado": "Carne, Aves y Productos Cárnicos",
    "embutidos": "Carne, Aves y Productos Cárnicos", "imperial clásica": "Carne, Aves y Productos Cárnicos",
    "blonda": "Carne, Aves y Productos Cárnicos", "solomillo vacuno": "Carne, Aves y Productos Cárnicos",
    "lomo de cebo de campo": "Carne, Aves y Productos Cárnicos", "lomo gran reserva": "Carne, Aves y Productos Cárnicos",
    "presa embuchada": "Carne, Aves y Productos Cárnicos", "maletín surtido": "Carne, Aves y Productos Cárnicos",
    "limo embuchado": "Carne, Aves y Productos Cárnicos", "lomo cebo": "Carne, Aves y Productos Cárnicos",

    # 🐟 PESCADOS, MARISCOS Y DERIVADOS
    "pescado": "Pescados, Mariscos y Derivados", "mariscos": "Pescados, Mariscos y Derivados",
    "productos del mar": "Pescados, Mariscos y Derivados", "atún": "Pescados, Mariscos y Derivados",
    "molusco": "Pescados, Mariscos y Derivados", "mejillones": "Pescados, Mariscos y Derivados",
    "anchoa": "Pescados, Mariscos y Derivados", "bonito": "Pescados, Mariscos y Derivados",
    "calamares": "Pescados, Mariscos y Derivados", "sardinilla": "Pescados, Mariscos y Derivados",
    "sardinas": "Pescados, Mariscos y Derivados", "jurel": "Pescados, Mariscos y Derivados",
    "potón": "Pescados, Mariscos y Derivados", "gambas": "Pescados, Mariscos y Derivados",
    "tortillitas de camarón": "Pescados, Mariscos y Derivados", "vientresa": "Pescados, Mariscos y Derivados",

    # 🌾 CEREALES, PANADERÍA Y PASTA
    "cereales": "Cereales, Panadería y Pasta", "pan": "Cereales, Panadería y Pasta", "galletas": "Cereales, Panadería y Pasta",
    "pasta": "Cereales, Panadería y Pasta", "arroz": "Cereales, Panadería y Pasta", "harina": "Cereales, Panadería y Pasta",
    "copos": "Cereales, Panadería y Pasta", "tortillas chips": "Cereales, Panadería y Pasta",
    "pasta spaghetti": "Cereales, Panadería y Pasta", "fusilli": "Cereales, Panadería y Pasta",
    "cracker": "Cereales, Panadería y Pasta", "tostada crujiente": "Cereales, Panadería y Pasta",
    "hojaldre": "Cereales, Panadería y Pasta", "quinoa": "Cereales, Panadería y Pasta", "brioches": "Cereales, Panadería y Pasta",

    # 🥕 FRUTAS, VERDURAS Y LEGUMBRES (Incluye Frutos Secos y Aceitunas)
    "vegetal": "Frutas, Verduras y Legumbres", "verdura": "Frutas, Verduras y Legumbres", "fruta": "Frutas, Verduras y Legumbres",
    "legumbres": "Frutas, Verduras y Legumbres", "patatas": "Frutas, Verduras y Legumbres", "clementinas": "Frutas, Verduras y Legumbres",
    "champiñón": "Frutas, Verduras y Legumbres", "uva": "Frutas, Verduras y Legumbres", "alcachofa": "Frutas, Verduras y Legumbres",
    "almendras": "Frutas, Verduras y Legumbres", "manzana": "Frutas, Verduras y Legumbres", "garbanzo": "Frutas, Verduras y Legumbres",
    "guisantes": "Frutas, Verduras y Legumbres", "maíz dulce": "Frutas, Verduras y Legumbres", "zanahoria": "Frutas, Verduras y Legumbres",
    "espinacas": "Frutas, Verduras y Legumbres", "tomate cherry": "Frutas, Verduras y Legumbres", "piña": "Frutas, Verduras y Legumbres",
    "remolacha": "Frutas, Verduras y Legumbres", "frutos secos": "Frutas, Verduras y Legumbres", "lenteja": "Frutas, Verduras y Legumbres",
    "habas": "Frutas, Verduras y Legumbres", "plátano": "Frutas, Verduras y Legumbres", "sandia": "Frutas, Verduras y Legumbres",
    "judía": "Frutas, Verduras y Legumbres", "melón": "Frutas, Verduras y Legumbres", "tomates 1kg": "Frutas, Verduras y Legumbres",
    "pementos": "Frutas, Verduras y Legumbres", "orejones": "Frutas, Verduras y Legumbres", "chía": "Frutas, Verduras y Legumbres",
    "mongeta": "Frutas, Verduras y Legumbres", "nature of nuts": "Frutas, Verduras y Legumbres", "lúcuma": "Frutas, Verduras y Legumbres",
    "aceitunas verdes": "Frutas, Verduras y Legumbres", "brote de soja": "Frutas, Verduras y Legumbres", "aceitunas aliñadas": "Frutas, Verduras y Legumbres",
    "castaña": "Frutas, Verduras y Legumbres", "pimientos de piquillo": "Frutas, Verduras y Legumbres", "kiwi deshidratado": "Frutas, Verduras y Legumbres",
    "melocoton fresquilla": "Frutas, Verduras y Legumbres", "frambuesa liofilizada": "Frutas, Verduras y Legumbres",
    "melocotón fresquilla": "Frutas, Verduras y Legumbres",

    # 🍬 SNACKS, DULCES Y POSTRES
    "snack": "Snacks, Dulces y Postres", "postres": "Snacks, Dulces y Postres", "chocolate": "Snacks, Dulces y Postres",
    "dulce": "Snacks, Dulces y Postres", "helado": "Snacks, Dulces y Postres", "pasteles": "Snacks, Dulces y Postres",
    "bollería": "Snacks, Dulces y Postres", "mermelada": "Snacks, Dulces y Postres", "palomitas": "Snacks, Dulces y Postres",
    "bizcochos": "Snacks, Dulces y Postres", "chips": "Snacks, Dulces y Postres", "polvorón": "Snacks, Dulces y Postres",
    "magdalenas": "Snacks, Dulces y Postres", "tortas de aceite": "Snacks, Dulces y Postres", "sirope": "Snacks, Dulces y Postres",
    "croissant": "Snacks, Dulces y Postres", "turrón": "Snacks, Dulces y Postres", "lazos": "Snacks, Dulces y Postres",
    "mantecados": "Snacks, Dulces y Postres", "trufa": "Snacks, Dulces y Postres", "bombón": "Snacks, Dulces y Postres",
    "coquitos": "Snacks, Dulces y Postres", "roscón": "Snacks, Dulces y Postres", "gominola": "Snacks, Dulces y Postres",
    "palmeron": "Snacks, Dulces y Postres", "azúcares": "Snacks, Dulces y Postres", "bocaditos": "Snacks, Dulces y Postres",
    "bimbachitos": "Snacks, Dulces y Postres", "cruji-bom": "Snacks, Dulces y Postres", "lacasitos": "Snacks, Dulces y Postres",
    "hojaldrina": "Snacks, Dulces y Postres", "bienmesabe": "Snacks, Dulces y Postres", "confettis": "Snacks, Dulces y Postres",
    "galletó": "Snacks, Dulces y Postres", "sobao": "Snacks, Dulces y Postres", "postre de almendra": "Snacks, Dulces y Postres",
    "mini surtido": "Snacks, Dulces y Postres", "bizcocho de nueces": "Snacks, Dulces y Postres", "choco lite": "Snacks, Dulces y Postres",
    "mikado": "Snacks, Dulces y Postres", "pom-bear": "Snacks, Dulces y Postres", "turrón crocant": "Snacks, Dulces y Postres",
    "corbatas": "Snacks, Dulces y Postres", "mini magdalenas": "Snacks, Dulces y Postres", "risueños": "Snacks, Dulces y Postres",
    "crema de membrillo": "Snacks, Dulces y Postres", "galleta ecologica": "Snacks, Dulces y Postres", "surtido mixto": "Snacks, Dulces y Postres",
    "surtido tradicional": "Snacks, Dulces y Postres", "delizias avena": "Snacks, Dulces y Postres", "morenitas": "Snacks, Dulces y Postres",
    "guirlache": "Snacks, Dulces y Postres", "minichocos": "Snacks, Dulces y Postres", "cortadillo": "Snacks, Dulces y Postres",
    "surtido especial": "Snacks, Dulces y Postres", "rabitos royale": "Snacks, Dulces y Postres", "cañas integrales": "Snacks, Dulces y Postres",
    "energy balls": "Snacks, Dulces y Postres", "monerris": "Snacks, Dulces y Postres", "mixto especial": "Snacks, Dulces y Postres",
    "sultanas": "Snacks, Dulces y Postres", "assortit": "Snacks, Dulces y Postres", "birba": "Snacks, Dulces y Postres",
    "bombon crocanti": "Snacks, Dulces y Postres",
    "galleta ecológica 240 gr": "Snacks, Dulces y Postres",
    "bizcocho al cacao": "Snacks, Dulces y Postres",
    "galleta tostada": "Snacks, Dulces y Postres",

    # 🍲 COMIDAS PREPARADAS Y ENVASADAS
    "conservas": "Comidas Preparadas y Envasadas", "comida preparada": "Comidas Preparadas y Envasadas",
    "sopas": "Comidas Preparadas y Envasadas", "platos preparados": "Comidas Preparadas y Envasadas",
    "caldo": "Comidas Preparadas y Envasadas", "puré de patata": "Comidas Preparadas y Envasadas",
    "tortilla de patata": "Comidas Preparadas y Envasadas", "lasaña": "Comidas Preparadas y Envasadas",
    "empanada": "Comidas Preparadas y Envasadas", "hummus": "Comidas Preparadas y Envasadas",
    "croquetas": "Comidas Preparadas y Envasadas", "ensalada cesar": "Comidas Preparadas y Envasadas",
    "gachamiga": "Comidas Preparadas y Envasadas", "wrap": "Comidas Preparadas y Envasadas",
    "gazpacho": "Comidas Preparadas y Envasadas", "salteado": "Comidas Preparadas y Envasadas",
    "alubias cocidas": "Comidas Preparadas y Envasadas", "avecrem": "Comidas Preparadas y Envasadas",
    "tentempie": "Comidas Preparadas y Envasadas", "croissant serrano": "Comidas Preparadas y Envasadas",
    "croissant mixto": "Comidas Preparadas y Envasadas", "panini": "Comidas Preparadas y Envasadas",
    "ensalada china": "Comidas Preparadas y Envasadas", "caldo natural": "Comidas Preparadas y Envasadas",
    "crema de lomo": "Comidas Preparadas y Envasadas", "puré de patata con zanahoria": "Comidas Preparadas y Envasadas",
    "tinga de pollo": "Comidas Preparadas y Envasadas", "napolitana mixta": "Comidas Preparadas y Envasadas",
    "viena": "Comidas Preparadas y Envasadas", "viena jamon serrano": "Comidas Preparadas y Envasadas",
    
    "croisant serrano lm": "Comidas Preparadas y Envasadas", 
    "croisant mixto lm": "Comidas Preparadas y Envasadas",   
    
    "alubias blancas cocidas 540g": "Comidas Preparadas y Envasadas",
    "alubias blancas cocidas": "Comidas Preparadas y Envasadas",
    "vienesa jamon serrano lm": "Comidas Preparadas y Envasadas",
    "tentempié crujiente": "Comidas Preparadas y Envasadas",
    "tentenpié crujiente": "Comidas Preparadas y Envasadas",

    # 🍾 BEBIDAS, AGUA E INFUSIONES
    "bebidas": "Bebidas, Agua e Infusiones", "zumos": "Bebidas, Agua e Infusiones", "agua": "Bebidas, Agua e Infusiones",
    "infusiones": "Bebidas, Agua e Infusiones", "café": "Bebidas, Agua e Infusiones", "té": "Bebidas, Agua e Infusiones",
    "agua mineral": "Bebidas, Agua e Infusiones", "zumo de naranja": "Bebidas, Agua e Infusiones", "cola cao": "Bebidas, Agua e Infusiones",
    "bebida arroz": "Bebidas, Agua e Infusiones", "manzanilla": "Bebidas, Agua e Infusiones", "ice tea": "Bebidas, Agua e Infusiones",
    "limonada": "Bebidas, Agua e Infusiones", "tila": "Bebidas, Agua e Infusiones", "infusión": "Bebidas, Agua e Infusiones",
    "batido": "Bebidas, Agua e Infusiones", "sport drink": "Bebidas, Agua e Infusiones", "kombucha": "Bebidas, Agua e Infusiones",
    "aloe vera": "Bebidas, Agua e Infusiones", "refresco": "Bebidas, Agua e Infusiones", "aqua de mar": "Bebidas, Agua e Infusiones",
    "cola de caballo": "Bebidas, Agua e Infusiones", "hinojo": "Bebidas, Agua e Infusiones", "hierbas naturales": "Bebidas, Agua e Infusiones",
    "cafe viaggio": "Bebidas, Agua e Infusiones",

    # 🍷 BEBIDAS ALCOHÓLICAS
    "bebidas alcohólicas": "Bebidas Alcohólicas", "cervezas": "Bebidas Alcohólicas", "vino": "Bebidas Alcohólicas",
    "beer": "Bebidas Alcohólicas", "verdejo": "Bebidas Alcohólicas", "crianza": "Bebidas Alcohólicas",
    "viña esmeralda": "Bebidas Alcohólicas", "altos de tamaron": "Bebidas Alcohólicas",

    # 🧂 SALSAS, CONDIMENTOS Y ADITIVOS
    "salsas": "Salsas, Condimentos y Aditivos", "condimentos": "Salsas, Condimentos y Aditivos",
    "vinagre": "Salsas, Condimentos y Aditivos", "aditivos": "Salsas, Condimentos y Aditivos",
    "especias": "Salsas, Condimentos y Aditivos", "mostaza": "Salsas, Condimentos y Aditivos",
    "sal": "Salsas, Condimentos y Aditivos", "tomate frito": "Salsas, Condimentos y Aditivos",
    "tomate triturado": "Salsas, Condimentos y Aditivos", "edulzante": "Salsas, Condimentos y Aditivos",
    "eritritol": "Salsas, Condimentos y Aditivos", "stevia": "Salsas, Condimentos y Aditivos",
    "truvía": "Salsas, Condimentos y Aditivos", "azúcar de coco": "Salsas, Condimentos y Aditivos",
    "miel": "Salsas, Condimentos y Aditivos", "cacao puro": "Salsas, Condimentos y Aditivos",
    "mayonesa": "Salsas, Condimentos y Aditivos", "ajo y finas hierbas": "Salsas, Condimentos y Aditivos",
    "mustard": "Salsas, Condimentos y Aditivos", "orlando": "Salsas, Condimentos y Aditivos",
    "tomate pelado": "Salsas, Condimentos y Aditivos", "tomte": "Salsas, Condimentos y Aditivos",
    "impulsor": "Salsas, Condimentos y Aditivos", "melaza": "Salsas, Condimentos y Aditivos",
    "miel de flores": "Salsas, Condimentos y Aditivos", "erythritol": "Salsas, Condimentos y Aditivos",
    "sazonador": "Salsas, Condimentos y Aditivos", "jengibre puro": "Salsas, Condimentos y Aditivos",
    "preparado barbacoa": "Salsas, Condimentos y Aditivos", "tomate entero": "Salsas, Condimentos y Aditivos",

    # 🍶 ACEITES, GRASAS Y PRODUCTOS SIMILARES
    "aceites y grasas": "Aceites, Grasas y Productos Similares", "aceites de oliva": "Aceites, Grasas y Productos Similares",
    "aceite de oliva": "Aceites, Grasas y Productos Similares", "aceite": "Aceites, Grasas y Productos Similares",
    "aceite de coco": "Aceites, Grasas y Productos Similares", "vierge": "Aceites, Grasas y Productos Similares",

    # 💊 SUPLEMENTOS Y ARTÍCULOS NO ALIMENTARIOS
    "vitaminas": "Suplementos y Artículos No Alimentarios", "crema facial": "Suplementos y Artículos No Alimentarios",
    "micellar casein": "Suplementos y Artículos No Alimentarios", "collmar": "Suplementos y Artículos No Alimentarios",
    "drasanvi": "Suplementos y Artículos No Alimentarios", "b36 drenante": "Suplementos y Artículos No Alimentarios",
    "polen": "Suplementos y Artículos No Alimentarios", "goma de borrar": "Suplementos y Artículos No Alimentarios",
    "caja hermética": "Suplementos y Artículos No Alimentarios", "oos": "Suplementos y Artículos No Alimentarios",
    "randa": "Suplementos y Artículos No Alimentarios", "xu fatopía": "Suplementos y Artículos No Alimentarios",
    "mast-lax": "Suplementos y Artículos No Alimentarios", "be zero": "Suplementos y Artículos No Alimentarios",
    "be4": "Suplementos y Artículos No Alimentarios", "desafío quiz": "Suplementos y Artículos No Alimentarios",
    "bulgarets": "Suplementos y Artículos No Alimentarios", "pelota furbo": "Suplementos y Artículos No Alimentarios",
    "big jl": "Suplementos y Artículos No Alimentarios", "sabores de españa": "Suplementos y Artículos No Alimentarios",
    "11": "Suplementos y Artículos No Alimentarios", "ooo": "Suplementos y Artículos No Alimentarios",
    "modernisme": "Suplementos y Artículos No Alimentarios", "flor de esquino": "Suplementos y Artículos No Alimentarios",
    "frised limon": "Suplementos y Artículos No Alimentarios", "vegan friendly": "Suplementos y Artículos No Alimentarios",
    "piura peru": "Suplementos y Artículos No Alimentarios", "marluc": "Suplementos y Artículos No Alimentarios",
    "xufatopía": "Suplementos y Artículos No Alimentarios", "b-live": "Suplementos y Artículos No Alimentarios",
    "vitamin c gummies": "Suplementos y Artículos No Alimentarios",
}

colores_nova = ['#44AA44', '#DDDD44', '#FFAA00', '#CC4444']
colores = ['#00814B', '#8CE700','#FFD500', '#FF8121', '#E11E10']
nutri_orden = ['a', 'b', 'c', 'd', 'e']
orden_nova = [1.0, 2.0, 3.0, 4.0]

